### ISSUE TITLE
The startup sequence is stuck in an infinite loop.

### ISSUE THREAD

**Issue by HVilaverde** [jostroOS/AmogDOS#3]
Self-explanatory. It's not due to Calamares' startup command, it is a bug in the code itself. What the hell did I do?﻿

**Comment by HVilaverde** [comment]
Will attempt a fix by removing the global max. list size, Check commit: 30dd150a7bfd54a5ff113e3a407ed64ae9be4855﻿

**Comment by HVilaverde** [comment]
Did not test previous solution yet, but if it does not work, then the problem may be related to a wrong working directory,﻿

**Comment by HVilaverde** [comment]
Global max. listsize is not the issue... i'm going to go insane.﻿

**Comment by mobilegmYT** [comment]
Revert all the recent previous commits and redo them from scratch?

**Comment by HVilaverde** [comment]
Problem is present on previous version of the software... will test to see if it's an issue with the image itself, as this was not present before.﻿

**Comment by HVilaverde** [comment]
WAIT I THINK I FUCKING ADDED THE AUTOSTARTUP TO THE SHELL PROFILE AAAAAAA I HOPE THIS IS NOT THE DAMN ISSUE AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA﻿

**Comment by HVilaverde** [comment]
Yes... i added it to the profile, that is the issue and it did not present itself before because of a previous limitation on active xorg instances. I need a break for today, my idiocy overwhelms me.﻿

**Comment by moon1789** [comment]
sus

**Comment by mobilegmYT** [comment]
This issue looks like every sterotpyical gh issue ever

1. Describe issue
2. List possible and complex fix for issue
3. Fix didn't work
4. Debugging
5. Spams in all caps that it was actually a minor mistake
6. Self hate
